CREATE TABLE public.products
(
    product_id
        BIGINT unique not null primary key
        GENERATED BY DEFAULT AS IDENTITY,
    product_name
        VARCHAR(40)   not null,
    product_price
        NUMERIC(5,2)  not null
);
ALTER TABLE public.products
    add constraint product_name_uc UNIQUE (product_name);