CREATE TABLE public.receipts
(
    receipt_id BIGINT unique       not null primary key
        GENERATED BY DEFAULT AS IDENTITY,
    receipt_date TIMESTAMP default now(),
    receipt_cashier BIGINT not null ,
    receipt_market BIGINT not null

);