CREATE TABLE public.cashiers
(
    cashier_id
                      BIGINT unique
                                  not null primary key
        GENERATED BY DEFAULT AS IDENTITY,
    cashier_name      VARCHAR(40) not null,
    cashier_last_name VARCHAR(40) not null,
    cashier_market    BIGINT      not null
);
ALTER TABLE public.cashiers
    add constraint cashier_fullname_uc
        UNIQUE (cashier_name, cashier_last_name);
