ALTER TABLE public.receipts
    add constraint receipt_cashier_fk
        foreign key (receipt_cashier)
            references public.cashier (cashier_id)
            ON DELETE RESTRICT;
ALTER TABLE public.receipts
    add constraint receipt_market_fk
        foreign key (receipt_market)
            references public.markets (market_id)
            ON DELETE RESTRICT;