INSERT INTO market_products(mp_product, mp_market, mp_in_warehouse)
VALUES (f_get_product_id_by_name('огурец'),
        f_get_market_id_by_name('ATB #1'),
        1713),
       (f_get_product_id_by_name('ананас'),
        f_get_market_id_by_name('ATB #1'),
        4866),
       (f_get_product_id_by_name('лук'),
        f_get_market_id_by_name('ATB #1'),
        4481),
       (f_get_product_id_by_name('мясо лось'),
        f_get_market_id_by_name('ATB #1'),
        90),
       (f_get_product_id_by_name('мясо заяц'),
        f_get_market_id_by_name('ATB #1'),
        1695),
       (f_get_product_id_by_name('курица мясо'),
        f_get_market_id_by_name('ATB #1'),
        2853),
       (f_get_product_id_by_name('Картофель'),
        f_get_market_id_by_name('ATB #1'),
        2447),
       (f_get_product_id_by_name('Чеснок'),
        f_get_market_id_by_name('ATB #1'),
        2421),
       (f_get_product_id_by_name('Петрушка'),
        f_get_market_id_by_name('ATB #1'),
        631),
       (f_get_product_id_by_name('Яблоки'),
        f_get_market_id_by_name('ATB #1'),
        2361),
       (f_get_product_id_by_name('бананы'),
        f_get_market_id_by_name('ATB #1'),
        526),
       (f_get_product_id_by_name('Масло сливочное'),
        f_get_market_id_by_name('ATB #1'),
        2769),
       (f_get_product_id_by_name('Кефир'),
        f_get_market_id_by_name('ATB #1'),
        471),
       (f_get_product_id_by_name('Молоко детское'),
        f_get_market_id_by_name('ATB #1'),
        3883),
       (f_get_product_id_by_name('Сметана'),
        f_get_market_id_by_name('ATB #1'),
        1578),
       (f_get_product_id_by_name('Творог'),
        f_get_market_id_by_name('ATB #1'),
        762),
       (f_get_product_id_by_name('Горчица'),
        f_get_market_id_by_name('ATB #1'),
        1187),
       (f_get_product_id_by_name('Малиновое варенье'),
        f_get_market_id_by_name('ATB #1'),
        930),
       (f_get_product_id_by_name('Консервированный горошек'),
        f_get_market_id_by_name('ATB #1'),
        1723),
       (f_get_product_id_by_name('Консервированная кукуруза'),
        f_get_market_id_by_name('ATB #1'),
        4234),
       (f_get_product_id_by_name('Детское питание'),
        f_get_market_id_by_name('ATB #1'),
        1656),
       (f_get_product_id_by_name('Сгущенка'),
        f_get_market_id_by_name('ATB #1'),
        4822),
       (f_get_product_id_by_name('Мед'),
        f_get_market_id_by_name('ATB #1'),
        2517),
       (f_get_product_id_by_name('Соевый соус'),
        f_get_market_id_by_name('ATB #1'),
        2023),
       (f_get_product_id_by_name('Баллончик со сливками'),
        f_get_market_id_by_name('ATB #1'),
        3993),
       (f_get_product_id_by_name('Фрикадельки полуфабрикат'),
        f_get_market_id_by_name('ATB #1'),
        2670),
       (f_get_product_id_by_name('Суповой набор мясной'),
        f_get_market_id_by_name('ATB #1'),
        2804),
       (f_get_product_id_by_name('Готовый куриный бульон'),
        f_get_market_id_by_name('ATB #1'),
        3949),
       (f_get_product_id_by_name('Курица бедра'),
        f_get_market_id_by_name('ATB #1'),
        3036),
       (f_get_product_id_by_name('Куриное филе'),
        f_get_market_id_by_name('ATB #1'),
        2403),
       (f_get_product_id_by_name('Свинина порционная по 300 г'),
        f_get_market_id_by_name('ATB #1'),
        2966),
       (f_get_product_id_by_name('Маргарин'),
        f_get_market_id_by_name('ATB #1'),
        1665),
       (f_get_product_id_by_name('Сливочное масло'),
        f_get_market_id_by_name('ATB #1'),
        3489),
       (f_get_product_id_by_name('смородина'),
        f_get_market_id_by_name('ATB #1'),
        972),
       (f_get_product_id_by_name('клубника'),
        f_get_market_id_by_name('ATB #1'),
        2532),
       (f_get_product_id_by_name('Отварные грибы'),
        f_get_market_id_by_name('ATB #1'),
        4536),
       (f_get_product_id_by_name('Слоеное тесто'),
        f_get_market_id_by_name('ATB #1'),
        2728),
       (f_get_product_id_by_name('лосось'),
        f_get_market_id_by_name('ATB #1'),
        1822),
       (f_get_product_id_by_name('карп'),
        f_get_market_id_by_name('ATB #1'),
        281),
       (f_get_product_id_by_name('карась'),
        f_get_market_id_by_name('ATB #1'),
        4501),
       (f_get_product_id_by_name('семга'),
        f_get_market_id_by_name('ATB #1'),
        4597),
       (f_get_product_id_by_name('Крабовые палочки'),
        f_get_market_id_by_name('ATB #1'),
        1484),
       (f_get_product_id_by_name('Мука пшеничная'),
        f_get_market_id_by_name('ATB #1'),
        3238),
       (f_get_product_id_by_name('Мука ржаная'),
        f_get_market_id_by_name('ATB #1'),
        4266),
       (f_get_product_id_by_name('Дрожжи сухие'),
        f_get_market_id_by_name('ATB #1'),
        1815),
       (f_get_product_id_by_name('Сода'),
        f_get_market_id_by_name('ATB #1'),
        4908),
       (f_get_product_id_by_name('Сахар обычный'),
        f_get_market_id_by_name('ATB #1'),
        2591),
       (f_get_product_id_by_name('Горький шоколад – 100 г'),
        f_get_market_id_by_name('ATB #1'),
        1781),
       (f_get_product_id_by_name('Гречка'),
        f_get_market_id_by_name('ATB #1'),
        4518),
       (f_get_product_id_by_name('Перловка'),
        f_get_market_id_by_name('ATB #1'),
        1455),
       (f_get_product_id_by_name('Рис'),
        f_get_market_id_by_name('ATB #1'),
        4988),
       (f_get_product_id_by_name('Овсяные хлопья'),
        f_get_market_id_by_name('ATB #1'),
        1785),
       (f_get_product_id_by_name('Кукурузная крупа'),
        f_get_market_id_by_name('ATB #1'),
        103),
       (f_get_product_id_by_name('Макароны спиральки'),
        f_get_market_id_by_name('ATB #1'),
        4105),
       (f_get_product_id_by_name('Горох'),
        f_get_market_id_by_name('ATB #1'),
        463),
       (f_get_product_id_by_name('Фасоль'),
        f_get_market_id_by_name('ATB #1'),
        257),
       (f_get_product_id_by_name('Панировочные сухари'),
        f_get_market_id_by_name('ATB #1'),
        4117),
       (f_get_product_id_by_name('Ваниль'),
        f_get_market_id_by_name('ATB #1'),
        1177),
       (f_get_product_id_by_name('Корица'),
        f_get_market_id_by_name('ATB #1'),
        1346),
       (f_get_product_id_by_name('Карри'),
        f_get_market_id_by_name('ATB #1'),
        3759),
       (f_get_product_id_by_name('Черный перец'),
        f_get_market_id_by_name('ATB #1'),
        571),
       (f_get_product_id_by_name('Красный перец'),
        f_get_market_id_by_name('ATB #1'),
        59),
       (f_get_product_id_by_name('Соль'),
        f_get_market_id_by_name('ATB #1'),
        703),
       (f_get_product_id_by_name('Паприка'),
        f_get_market_id_by_name('ATB #1'),
        4614),
       (f_get_product_id_by_name('Лавровый лист'),
        f_get_market_id_by_name('ATB #1'),
        37),
       (f_get_product_id_by_name('Чай'),
        f_get_market_id_by_name('ATB #1'),
        4867),
       (f_get_product_id_by_name('кофе'),
        f_get_market_id_by_name('ATB #1'),
        1249),
       (f_get_product_id_by_name('Кофе растворимый'),
        f_get_market_id_by_name('ATB #1'),
        2062),
       (f_get_product_id_by_name('Чай черный'),
        f_get_market_id_by_name('ATB #1'),
        3068),
       (f_get_product_id_by_name('Чай зеленый'),
        f_get_market_id_by_name('ATB #1'),
        1958),
       (f_get_product_id_by_name('Чай мятный'),
        f_get_market_id_by_name('ATB #1'),
        3457),
       (f_get_product_id_by_name('Какао порошок'),
        f_get_market_id_by_name('ATB #1'),
        2460),
       (f_get_product_id_by_name('огурец'),
        f_get_market_id_by_name('ATB #2'),
        3261),
       (f_get_product_id_by_name('ананас'),
        f_get_market_id_by_name('ATB #2'),
        3562),
       (f_get_product_id_by_name('лук'),
        f_get_market_id_by_name('ATB #2'),
        2530),
       (f_get_product_id_by_name('мясо заяц'),
        f_get_market_id_by_name('ATB #2'),
        4520),
       (f_get_product_id_by_name('курица мясо'),
        f_get_market_id_by_name('ATB #2'),
        827),
       (f_get_product_id_by_name('капуста'),
        f_get_market_id_by_name('ATB #2'),
        1774),
       (f_get_product_id_by_name('Чеснок'),
        f_get_market_id_by_name('ATB #2'),
        3422),
       (f_get_product_id_by_name('Петрушка'),
        f_get_market_id_by_name('ATB #2'),
        4849),
       (f_get_product_id_by_name('Укроп'),
        f_get_market_id_by_name('ATB #2'),
        3434),
       (f_get_product_id_by_name('Яблоки'),
        f_get_market_id_by_name('ATB #2'),
        1924),
       (f_get_product_id_by_name('бананы'),
        f_get_market_id_by_name('ATB #2'),
        4968),
       (f_get_product_id_by_name('Масло сливочное'),
        f_get_market_id_by_name('ATB #2'),
        1934),
       (f_get_product_id_by_name('Кефир'),
        f_get_market_id_by_name('ATB #2'),
        204),
       (f_get_product_id_by_name('Молоко детское'),
        f_get_market_id_by_name('ATB #2'),
        4965),
       (f_get_product_id_by_name('Сметана'),
        f_get_market_id_by_name('ATB #2'),
        1973),
       (f_get_product_id_by_name('Творог'),
        f_get_market_id_by_name('ATB #2'),
        501),
       (f_get_product_id_by_name('Горчица'),
        f_get_market_id_by_name('ATB #2'),
        1248),
       (f_get_product_id_by_name('Консервированный горошек'),
        f_get_market_id_by_name('ATB #2'),
        1059),
       (f_get_product_id_by_name('Детское питание'),
        f_get_market_id_by_name('ATB #2'),
        4709),
       (f_get_product_id_by_name('Сгущенка'),
        f_get_market_id_by_name('ATB #2'),
        3603),
       (f_get_product_id_by_name('Мед'),
        f_get_market_id_by_name('ATB #2'),
        979),
       (f_get_product_id_by_name('Яйца'),
        f_get_market_id_by_name('ATB #2'),
        2943),
       (f_get_product_id_by_name('Соевый соус'),
        f_get_market_id_by_name('ATB #2'),
        4073),
       (f_get_product_id_by_name('Баллончик со сливками'),
        f_get_market_id_by_name('ATB #2'),
        4942),
       (f_get_product_id_by_name('Кошачий корм Вискас'),
        f_get_market_id_by_name('ATB #2'),
        3815),
       (f_get_product_id_by_name('Фрикадельки полуфабрикат'),
        f_get_market_id_by_name('ATB #2'),
        341),
       (f_get_product_id_by_name('Котлеты полуфабрикат'),
        f_get_market_id_by_name('ATB #2'),
        4289),
       (f_get_product_id_by_name('Суповой набор мясной'),
        f_get_market_id_by_name('ATB #2'),
        889),
       (f_get_product_id_by_name('Готовый мясной бульон'),
        f_get_market_id_by_name('ATB #2'),
        2542),
       (f_get_product_id_by_name('Готовый куриный бульон'),
        f_get_market_id_by_name('ATB #2'),
        581),
       (f_get_product_id_by_name('Курица бедра'),
        f_get_market_id_by_name('ATB #2'),
        2736),
       (f_get_product_id_by_name('Куриное филе'),
        f_get_market_id_by_name('ATB #2'),
        3659),
       (f_get_product_id_by_name('Стручковая фасоль'),
        f_get_market_id_by_name('ATB #2'),
        3535),
       (f_get_product_id_by_name('Маргарин'),
        f_get_market_id_by_name('ATB #2'),
        2340),
       (f_get_product_id_by_name('Сливочное масло'),
        f_get_market_id_by_name('ATB #2'),
        4784),
       (f_get_product_id_by_name('смородина'),
        f_get_market_id_by_name('ATB #2'),
        4421),
       (f_get_product_id_by_name('клубника'),
        f_get_market_id_by_name('ATB #2'),
        797),
       (f_get_product_id_by_name('Отварные грибы'),
        f_get_market_id_by_name('ATB #2'),
        3875),
       (f_get_product_id_by_name('Шпинат'),
        f_get_market_id_by_name('ATB #2'),
        2084),
       (f_get_product_id_by_name('селедка'),
        f_get_market_id_by_name('ATB #2'),
        3182),
       (f_get_product_id_by_name('толстолоб'),
        f_get_market_id_by_name('ATB #2'),
        2965),
       (f_get_product_id_by_name('семга'),
        f_get_market_id_by_name('ATB #2'),
        3502),
       (f_get_product_id_by_name('Мука пшеничная'),
        f_get_market_id_by_name('ATB #2'),
        3949),
       (f_get_product_id_by_name('Мука ржаная'),
        f_get_market_id_by_name('ATB #2'),
        1232),
       (f_get_product_id_by_name('Сода'),
        f_get_market_id_by_name('ATB #2'),
        3371),
       (f_get_product_id_by_name('Разрыхлитель теста'),
        f_get_market_id_by_name('ATB #2'),
        4593),
       (f_get_product_id_by_name('Сахар обычный'),
        f_get_market_id_by_name('ATB #2'),
        391),
       (f_get_product_id_by_name('Сахар коричневый'),
        f_get_market_id_by_name('ATB #2'),
        3314),
       (f_get_product_id_by_name('Желатин'),
        f_get_market_id_by_name('ATB #2'),
        2922),
       (f_get_product_id_by_name('Горький шоколад – 100 г'),
        f_get_market_id_by_name('ATB #2'),
        3086),
       (f_get_product_id_by_name('Крахмал'),
        f_get_market_id_by_name('ATB #2'),
        4986),
       (f_get_product_id_by_name('Масло оливковое'),
        f_get_market_id_by_name('ATB #2'),
        813),
       (f_get_product_id_by_name('Перловка'),
        f_get_market_id_by_name('ATB #2'),
        1194),
       (f_get_product_id_by_name('Рис'),
        f_get_market_id_by_name('ATB #2'),
        1854),
       (f_get_product_id_by_name('Манка'),
        f_get_market_id_by_name('ATB #2'),
        3455),
       (f_get_product_id_by_name('Кукурузная крупа'),
        f_get_market_id_by_name('ATB #2'),
        1146),
       (f_get_product_id_by_name('Макароны спиральки'),
        f_get_market_id_by_name('ATB #2'),
        1614),
       (f_get_product_id_by_name('Горох'),
        f_get_market_id_by_name('ATB #2'),
        2264),
       (f_get_product_id_by_name('Фасоль'),
        f_get_market_id_by_name('ATB #2'),
        3122),
       (f_get_product_id_by_name('Панировочные сухари'),
        f_get_market_id_by_name('ATB #2'),
        4199),
       (f_get_product_id_by_name('Сухие грибы'),
        f_get_market_id_by_name('ATB #2'),
        472),
       (f_get_product_id_by_name('Ваниль'),
        f_get_market_id_by_name('ATB #2'),
        4853),
       (f_get_product_id_by_name('Красный перец'),
        f_get_market_id_by_name('ATB #2'),
        433),
       (f_get_product_id_by_name('Паприка'),
        f_get_market_id_by_name('ATB #2'),
        2989),
       (f_get_product_id_by_name('Лавровый лист'),
        f_get_market_id_by_name('ATB #2'),
        1431),
       (f_get_product_id_by_name('кофе'),
        f_get_market_id_by_name('ATB #2'),
        71),
       (f_get_product_id_by_name('Кофе растворимый'),
        f_get_market_id_by_name('ATB #2'),
        459),
       (f_get_product_id_by_name('Чай зеленый'),
        f_get_market_id_by_name('ATB #2'),
        90),
       (f_get_product_id_by_name('Чай мятный'),
        f_get_market_id_by_name('ATB #2'),
        860),
       (f_get_product_id_by_name('ананас'),
        f_get_market_id_by_name('ATB #3'),
        87),
       (f_get_product_id_by_name('помидор'),
        f_get_market_id_by_name('ATB #3'),
        2881),
       (f_get_product_id_by_name('курица мясо'),
        f_get_market_id_by_name('ATB #3'),
        3378),
       (f_get_product_id_by_name('капуста'),
        f_get_market_id_by_name('ATB #3'),
        1156),
       (f_get_product_id_by_name('Морковь'),
        f_get_market_id_by_name('ATB #3'),
        364),
       (f_get_product_id_by_name('Чеснок'),
        f_get_market_id_by_name('ATB #3'),
        390),
       (f_get_product_id_by_name('Укроп'),
        f_get_market_id_by_name('ATB #3'),
        2192),
       (f_get_product_id_by_name('Яблоки'),
        f_get_market_id_by_name('ATB #3'),
        756),
       (f_get_product_id_by_name('Кефир'),
        f_get_market_id_by_name('ATB #3'),
        506),
       (f_get_product_id_by_name('Молоко детское'),
        f_get_market_id_by_name('ATB #3'),
        2035),
       (f_get_product_id_by_name('Сметана'),
        f_get_market_id_by_name('ATB #3'),
        4720),
       (f_get_product_id_by_name('Сыр'),
        f_get_market_id_by_name('ATB #3'),
        3978),
       (f_get_product_id_by_name('Малиновое варенье'),
        f_get_market_id_by_name('ATB #3'),
        3633),
       (f_get_product_id_by_name('Томатная паста'),
        f_get_market_id_by_name('ATB #3'),
        3103),
       (f_get_product_id_by_name('Рыбная консерва'),
        f_get_market_id_by_name('ATB #3'),
        4582),
       (f_get_product_id_by_name('Консервированный горошек'),
        f_get_market_id_by_name('ATB #3'),
        1849),
       (f_get_product_id_by_name('Консервированная кукуруза'),
        f_get_market_id_by_name('ATB #3'),
        890),
       (f_get_product_id_by_name('Детское питание'),
        f_get_market_id_by_name('ATB #3'),
        135),
       (f_get_product_id_by_name('Сгущенка'),
        f_get_market_id_by_name('ATB #3'),
        797),
       (f_get_product_id_by_name('Мед'),
        f_get_market_id_by_name('ATB #3'),
        4505),
       (f_get_product_id_by_name('Яйца'),
        f_get_market_id_by_name('ATB #3'),
        2617),
       (f_get_product_id_by_name('Соевый соус'),
        f_get_market_id_by_name('ATB #3'),
        3553),
       (f_get_product_id_by_name('Уксус обычный'),
        f_get_market_id_by_name('ATB #3'),
        3616),
       (f_get_product_id_by_name('Фрикадельки полуфабрикат'),
        f_get_market_id_by_name('ATB #3'),
        2923),
       (f_get_product_id_by_name('Котлеты полуфабрикат'),
        f_get_market_id_by_name('ATB #3'),
        2915),
       (f_get_product_id_by_name('Суповой набор куриный'),
        f_get_market_id_by_name('ATB #3'),
        4784),
       (f_get_product_id_by_name('Суповой набор мясной'),
        f_get_market_id_by_name('ATB #3'),
        2089),
       (f_get_product_id_by_name('Готовый мясной бульон'),
        f_get_market_id_by_name('ATB #3'),
        3338),
       (f_get_product_id_by_name('Готовый куриный бульон'),
        f_get_market_id_by_name('ATB #3'),
        2803),
       (f_get_product_id_by_name('Курица бедра'),
        f_get_market_id_by_name('ATB #3'),
        3953),
       (f_get_product_id_by_name('Курица окорочка'),
        f_get_market_id_by_name('ATB #3'),
        1267),
       (f_get_product_id_by_name('Куриное филе'),
        f_get_market_id_by_name('ATB #3'),
        4045),
       (f_get_product_id_by_name('Свинина порционная по 300 г'),
        f_get_market_id_by_name('ATB #3'),
        1514),
       (f_get_product_id_by_name('Маргарин'),
        f_get_market_id_by_name('ATB #3'),
        66),
       (f_get_product_id_by_name('клюква'),
        f_get_market_id_by_name('ATB #3'),
        2361),
       (f_get_product_id_by_name('Шпинат'),
        f_get_market_id_by_name('ATB #3'),
        2636),
       (f_get_product_id_by_name('лосось'),
        f_get_market_id_by_name('ATB #3'),
        3637),
       (f_get_product_id_by_name('селедка'),
        f_get_market_id_by_name('ATB #3'),
        186),
       (f_get_product_id_by_name('карп'),
        f_get_market_id_by_name('ATB #3'),
        3628),
       (f_get_product_id_by_name('толстолоб'),
        f_get_market_id_by_name('ATB #3'),
        296),
       (f_get_product_id_by_name('семга'),
        f_get_market_id_by_name('ATB #3'),
        2435),
       (f_get_product_id_by_name('Крабовые палочки'),
        f_get_market_id_by_name('ATB #3'),
        4012),
       (f_get_product_id_by_name('Мука пшеничная'),
        f_get_market_id_by_name('ATB #3'),
        1327),
       (f_get_product_id_by_name('Дрожжи сухие'),
        f_get_market_id_by_name('ATB #3'),
        3683),
       (f_get_product_id_by_name('Сода'),
        f_get_market_id_by_name('ATB #3'),
        4131),
       (f_get_product_id_by_name('Разрыхлитель теста'),
        f_get_market_id_by_name('ATB #3'),
        3255),
       (f_get_product_id_by_name('Сахар обычный'),
        f_get_market_id_by_name('ATB #3'),
        3045),
       (f_get_product_id_by_name('Сахар коричневый'),
        f_get_market_id_by_name('ATB #3'),
        601),
       (f_get_product_id_by_name('Сахарная пудра'),
        f_get_market_id_by_name('ATB #3'),
        217),
       (f_get_product_id_by_name('Горький шоколад – 100 г'),
        f_get_market_id_by_name('ATB #3'),
        2825),
       (f_get_product_id_by_name('Крахмал'),
        f_get_market_id_by_name('ATB #3'),
        1096),
       (f_get_product_id_by_name('Масло оливковое'),
        f_get_market_id_by_name('ATB #3'),
        3703),
       (f_get_product_id_by_name('Гречка'),
        f_get_market_id_by_name('ATB #3'),
        312),
       (f_get_product_id_by_name('Рис'),
        f_get_market_id_by_name('ATB #3'),
        1870),
       (f_get_product_id_by_name('Овсяные хлопья'),
        f_get_market_id_by_name('ATB #3'),
        2548),
       (f_get_product_id_by_name('Манка'),
        f_get_market_id_by_name('ATB #3'),
        2002),
       (f_get_product_id_by_name('Кукурузная крупа'),
        f_get_market_id_by_name('ATB #3'),
        4868),
       (f_get_product_id_by_name('Макароны спагетти'),
        f_get_market_id_by_name('ATB #3'),
        4511),
       (f_get_product_id_by_name('Макароны спиральки'),
        f_get_market_id_by_name('ATB #3'),
        2942),
       (f_get_product_id_by_name('Горох'),
        f_get_market_id_by_name('ATB #3'),
        1156),
       (f_get_product_id_by_name('Фасоль'),
        f_get_market_id_by_name('ATB #3'),
        4037),
       (f_get_product_id_by_name('Панировочные сухари'),
        f_get_market_id_by_name('ATB #3'),
        1173),
       (f_get_product_id_by_name('Корица'),
        f_get_market_id_by_name('ATB #3'),
        1807),
       (f_get_product_id_by_name('Карри'),
        f_get_market_id_by_name('ATB #3'),
        182),
       (f_get_product_id_by_name('Красный перец'),
        f_get_market_id_by_name('ATB #3'),
        4117),
       (f_get_product_id_by_name('Соль'),
        f_get_market_id_by_name('ATB #3'),
        1901),
       (f_get_product_id_by_name('Паприка'),
        f_get_market_id_by_name('ATB #3'),
        914),
       (f_get_product_id_by_name('Куркума'),
        f_get_market_id_by_name('ATB #3'),
        3066),
       (f_get_product_id_by_name('Лавровый лист'),
        f_get_market_id_by_name('ATB #3'),
        1453),
       (f_get_product_id_by_name('Кофе растворимый'),
        f_get_market_id_by_name('ATB #3'),
        1761),
       (f_get_product_id_by_name('Чай черный'),
        f_get_market_id_by_name('ATB #3'),
        714),
       (f_get_product_id_by_name('Чай зеленый'),
        f_get_market_id_by_name('ATB #3'),
        906),
       (f_get_product_id_by_name('Какао порошок'),
        f_get_market_id_by_name('ATB #3'),
        824),
       (f_get_product_id_by_name('ананас'),
        f_get_market_id_by_name('ATB #4'),
        283),
       (f_get_product_id_by_name('лук'),
        f_get_market_id_by_name('ATB #4'),
        531),
       (f_get_product_id_by_name('помидор'),
        f_get_market_id_by_name('ATB #4'),
        307),
       (f_get_product_id_by_name('мясо лось'),
        f_get_market_id_by_name('ATB #4'),
        1980),
       (f_get_product_id_by_name('курица мясо'),
        f_get_market_id_by_name('ATB #4'),
        2857),
       (f_get_product_id_by_name('Картофель'),
        f_get_market_id_by_name('ATB #4'),
        4451),
       (f_get_product_id_by_name('Морковь'),
        f_get_market_id_by_name('ATB #4'),
        359),
       (f_get_product_id_by_name('Петрушка'),
        f_get_market_id_by_name('ATB #4'),
        1757),
       (f_get_product_id_by_name('Укроп'),
        f_get_market_id_by_name('ATB #4'),
        2251),
       (f_get_product_id_by_name('Яблоки'),
        f_get_market_id_by_name('ATB #4'),
        1905),
       (f_get_product_id_by_name('бананы'),
        f_get_market_id_by_name('ATB #4'),
        559),
       (f_get_product_id_by_name('Творог'),
        f_get_market_id_by_name('ATB #4'),
        2951),
       (f_get_product_id_by_name('Сыр'),
        f_get_market_id_by_name('ATB #4'),
        2719),
       (f_get_product_id_by_name('Горчица'),
        f_get_market_id_by_name('ATB #4'),
        739),
       (f_get_product_id_by_name('Малиновое варенье'),
        f_get_market_id_by_name('ATB #4'),
        4969),
       (f_get_product_id_by_name('Томатная паста'),
        f_get_market_id_by_name('ATB #4'),
        4049),
       (f_get_product_id_by_name('Рыбная консерва'),
        f_get_market_id_by_name('ATB #4'),
        3633),
       (f_get_product_id_by_name('Консервированная кукуруза'),
        f_get_market_id_by_name('ATB #4'),
        3889),
       (f_get_product_id_by_name('Мед'),
        f_get_market_id_by_name('ATB #4'),
        279),
       (f_get_product_id_by_name('Яйца'),
        f_get_market_id_by_name('ATB #4'),
        857),
       (f_get_product_id_by_name('Масло растительное'),
        f_get_market_id_by_name('ATB #4'),
        4287),
       (f_get_product_id_by_name('Уксус обычный'),
        f_get_market_id_by_name('ATB #4'),
        2496),
       (f_get_product_id_by_name('Баллончик со сливками'),
        f_get_market_id_by_name('ATB #4'),
        652),
       (f_get_product_id_by_name('Кошачий корм Вискас'),
        f_get_market_id_by_name('ATB #4'),
        3233),
       (f_get_product_id_by_name('Фрикадельки полуфабрикат'),
        f_get_market_id_by_name('ATB #4'),
        1510),
       (f_get_product_id_by_name('Котлеты полуфабрикат'),
        f_get_market_id_by_name('ATB #4'),
        4787),
       (f_get_product_id_by_name('Суповой набор куриный'),
        f_get_market_id_by_name('ATB #4'),
        2728),
       (f_get_product_id_by_name('Суповой набор мясной'),
        f_get_market_id_by_name('ATB #4'),
        3274),
       (f_get_product_id_by_name('Готовый куриный бульон'),
        f_get_market_id_by_name('ATB #4'),
        2358),
       (f_get_product_id_by_name('Курица окорочка'),
        f_get_market_id_by_name('ATB #4'),
        3743),
       (f_get_product_id_by_name('Куриное филе'),
        f_get_market_id_by_name('ATB #4'),
        4762),
       (f_get_product_id_by_name('Стручковая фасоль'),
        f_get_market_id_by_name('ATB #4'),
        1061),
       (f_get_product_id_by_name('смородина'),
        f_get_market_id_by_name('ATB #4'),
        1470),
       (f_get_product_id_by_name('клубника'),
        f_get_market_id_by_name('ATB #4'),
        3293),
       (f_get_product_id_by_name('Шпинат'),
        f_get_market_id_by_name('ATB #4'),
        263),
       (f_get_product_id_by_name('Слоеное тесто'),
        f_get_market_id_by_name('ATB #4'),
        4973),
       (f_get_product_id_by_name('лосось'),
        f_get_market_id_by_name('ATB #4'),
        2141),
       (f_get_product_id_by_name('карп'),
        f_get_market_id_by_name('ATB #4'),
        3659),
       (f_get_product_id_by_name('карась'),
        f_get_market_id_by_name('ATB #4'),
        2529),
       (f_get_product_id_by_name('Крабовые палочки'),
        f_get_market_id_by_name('ATB #4'),
        1232),
       (f_get_product_id_by_name('Дрожжи сухие'),
        f_get_market_id_by_name('ATB #4'),
        970),
       (f_get_product_id_by_name('Сода'),
        f_get_market_id_by_name('ATB #4'),
        2426),
       (f_get_product_id_by_name('Разрыхлитель теста'),
        f_get_market_id_by_name('ATB #4'),
        2848),
       (f_get_product_id_by_name('Сахар обычный'),
        f_get_market_id_by_name('ATB #4'),
        248),
       (f_get_product_id_by_name('Сахарная пудра'),
        f_get_market_id_by_name('ATB #4'),
        1188),
       (f_get_product_id_by_name('Желатин'),
        f_get_market_id_by_name('ATB #4'),
        3950),
       (f_get_product_id_by_name('Горький шоколад – 100 г'),
        f_get_market_id_by_name('ATB #4'),
        3056),
       (f_get_product_id_by_name('Крахмал'),
        f_get_market_id_by_name('ATB #4'),
        4690),
       (f_get_product_id_by_name('Масло оливковое'),
        f_get_market_id_by_name('ATB #4'),
        4139),
       (f_get_product_id_by_name('Перловка'),
        f_get_market_id_by_name('ATB #4'),
        1198),
       (f_get_product_id_by_name('Рис'),
        f_get_market_id_by_name('ATB #4'),
        1380),
       (f_get_product_id_by_name('Овсяные хлопья'),
        f_get_market_id_by_name('ATB #4'),
        1061),
       (f_get_product_id_by_name('Манка'),
        f_get_market_id_by_name('ATB #4'),
        1261),
       (f_get_product_id_by_name('Кукурузная крупа'),
        f_get_market_id_by_name('ATB #4'),
        4300),
       (f_get_product_id_by_name('Макароны спагетти'),
        f_get_market_id_by_name('ATB #4'),
        640),
       (f_get_product_id_by_name('Макароны спиральки'),
        f_get_market_id_by_name('ATB #4'),
        2959),
       (f_get_product_id_by_name('Фасоль'),
        f_get_market_id_by_name('ATB #4'),
        1960),
       (f_get_product_id_by_name('Панировочные сухари'),
        f_get_market_id_by_name('ATB #4'),
        998),
       (f_get_product_id_by_name('Сухие грибы'),
        f_get_market_id_by_name('ATB #4'),
        3262),
       (f_get_product_id_by_name('Ваниль'),
        f_get_market_id_by_name('ATB #4'),
        4839),
       (f_get_product_id_by_name('Корица'),
        f_get_market_id_by_name('ATB #4'),
        899),
       (f_get_product_id_by_name('Карри'),
        f_get_market_id_by_name('ATB #4'),
        2778),
       (f_get_product_id_by_name('Красный перец'),
        f_get_market_id_by_name('ATB #4'),
        924),
       (f_get_product_id_by_name('Паприка'),
        f_get_market_id_by_name('ATB #4'),
        500),
       (f_get_product_id_by_name('Куркума'),
        f_get_market_id_by_name('ATB #4'),
        1365),
       (f_get_product_id_by_name('Лавровый лист'),
        f_get_market_id_by_name('ATB #4'),
        4463),
       (f_get_product_id_by_name('кофе'),
        f_get_market_id_by_name('ATB #4'),
        4605),
       (f_get_product_id_by_name('Кофе растворимый'),
        f_get_market_id_by_name('ATB #4'),
        1585),
       (f_get_product_id_by_name('Чай черный'),
        f_get_market_id_by_name('ATB #4'),
        4518),
       (f_get_product_id_by_name('Чай зеленый'),
        f_get_market_id_by_name('ATB #4'),
        806),
       (f_get_product_id_by_name('Какао порошок'),
        f_get_market_id_by_name('ATB #4'),
        988),
       (f_get_product_id_by_name('ананас'),
        f_get_market_id_by_name('ATB #5'),
        4972),
       (f_get_product_id_by_name('помидор'),
        f_get_market_id_by_name('ATB #5'),
        2044),
       (f_get_product_id_by_name('мясо лось'),
        f_get_market_id_by_name('ATB #5'),
        3015),
       (f_get_product_id_by_name('курица мясо'),
        f_get_market_id_by_name('ATB #5'),
        3245),
       (f_get_product_id_by_name('капуста'),
        f_get_market_id_by_name('ATB #5'),
        4427),
       (f_get_product_id_by_name('Картофель'),
        f_get_market_id_by_name('ATB #5'),
        1791),
       (f_get_product_id_by_name('Петрушка'),
        f_get_market_id_by_name('ATB #5'),
        835),
       (f_get_product_id_by_name('Укроп'),
        f_get_market_id_by_name('ATB #5'),
        1301),
       (f_get_product_id_by_name('Яблоки'),
        f_get_market_id_by_name('ATB #5'),
        1995),
       (f_get_product_id_by_name('бананы'),
        f_get_market_id_by_name('ATB #5'),
        1200),
       (f_get_product_id_by_name('Масло сливочное'),
        f_get_market_id_by_name('ATB #5'),
        2306),
       (f_get_product_id_by_name('Кефир'),
        f_get_market_id_by_name('ATB #5'),
        2308),
       (f_get_product_id_by_name('Молоко детское'),
        f_get_market_id_by_name('ATB #5'),
        2966),
       (f_get_product_id_by_name('Сметана'),
        f_get_market_id_by_name('ATB #5'),
        3746),
       (f_get_product_id_by_name('Творог'),
        f_get_market_id_by_name('ATB #5'),
        988),
       (f_get_product_id_by_name('Горчица'),
        f_get_market_id_by_name('ATB #5'),
        738),
       (f_get_product_id_by_name('Малиновое варенье'),
        f_get_market_id_by_name('ATB #5'),
        1090),
       (f_get_product_id_by_name('Томатная паста'),
        f_get_market_id_by_name('ATB #5'),
        4305),
       (f_get_product_id_by_name('Консервированный горошек'),
        f_get_market_id_by_name('ATB #5'),
        3098),
       (f_get_product_id_by_name('Консервированная кукуруза'),
        f_get_market_id_by_name('ATB #5'),
        3097),
       (f_get_product_id_by_name('Детское питание'),
        f_get_market_id_by_name('ATB #5'),
        4303),
       (f_get_product_id_by_name('Сгущенка'),
        f_get_market_id_by_name('ATB #5'),
        911),
       (f_get_product_id_by_name('Мед'),
        f_get_market_id_by_name('ATB #5'),
        446),
       (f_get_product_id_by_name('Яйца'),
        f_get_market_id_by_name('ATB #5'),
        93),
       (f_get_product_id_by_name('Масло растительное'),
        f_get_market_id_by_name('ATB #5'),
        1923),
       (f_get_product_id_by_name('Соевый соус'),
        f_get_market_id_by_name('ATB #5'),
        629),
       (f_get_product_id_by_name('Кошачий корм Вискас'),
        f_get_market_id_by_name('ATB #5'),
        1695),
       (f_get_product_id_by_name('Фрикадельки полуфабрикат'),
        f_get_market_id_by_name('ATB #5'),
        1113),
       (f_get_product_id_by_name('Котлеты полуфабрикат'),
        f_get_market_id_by_name('ATB #5'),
        4234),
       (f_get_product_id_by_name('Суповой набор куриный'),
        f_get_market_id_by_name('ATB #5'),
        1665),
       (f_get_product_id_by_name('Суповой набор мясной'),
        f_get_market_id_by_name('ATB #5'),
        4562),
       (f_get_product_id_by_name('Готовый мясной бульон'),
        f_get_market_id_by_name('ATB #5'),
        2078),
       (f_get_product_id_by_name('Готовый куриный бульон'),
        f_get_market_id_by_name('ATB #5'),
        3951),
       (f_get_product_id_by_name('Курица бедра'),
        f_get_market_id_by_name('ATB #5'),
        3314),
       (f_get_product_id_by_name('Куриное филе'),
        f_get_market_id_by_name('ATB #5'),
        2367),
       (f_get_product_id_by_name('Свинина порционная по 300 г'),
        f_get_market_id_by_name('ATB #5'),
        4219),
       (f_get_product_id_by_name('Сало'),
        f_get_market_id_by_name('ATB #5'),
        2151),
       (f_get_product_id_by_name('Стручковая фасоль'),
        f_get_market_id_by_name('ATB #5'),
        453),
       (f_get_product_id_by_name('Сливочное масло'),
        f_get_market_id_by_name('ATB #5'),
        82),
       (f_get_product_id_by_name('смородина'),
        f_get_market_id_by_name('ATB #5'),
        2320),
       (f_get_product_id_by_name('клубника'),
        f_get_market_id_by_name('ATB #5'),
        1842),
       (f_get_product_id_by_name('клюква'),
        f_get_market_id_by_name('ATB #5'),
        2375),
       (f_get_product_id_by_name('Отварные грибы'),
        f_get_market_id_by_name('ATB #5'),
        1285),
       (f_get_product_id_by_name('Слоеное тесто'),
        f_get_market_id_by_name('ATB #5'),
        1453),
       (f_get_product_id_by_name('лосось'),
        f_get_market_id_by_name('ATB #5'),
        3611),
       (f_get_product_id_by_name('селедка'),
        f_get_market_id_by_name('ATB #5'),
        2808),
       (f_get_product_id_by_name('карп'),
        f_get_market_id_by_name('ATB #5'),
        2552),
       (f_get_product_id_by_name('толстолоб'),
        f_get_market_id_by_name('ATB #5'),
        2582),
       (f_get_product_id_by_name('семга'),
        f_get_market_id_by_name('ATB #5'),
        3072),
       (f_get_product_id_by_name('Крабовые палочки'),
        f_get_market_id_by_name('ATB #5'),
        2593),
       (f_get_product_id_by_name('Дрожжи сухие'),
        f_get_market_id_by_name('ATB #5'),
        609),
       (f_get_product_id_by_name('Сода'),
        f_get_market_id_by_name('ATB #5'),
        3797),
       (f_get_product_id_by_name('Разрыхлитель теста'),
        f_get_market_id_by_name('ATB #5'),
        4962),
       (f_get_product_id_by_name('Сахар обычный'),
        f_get_market_id_by_name('ATB #5'),
        752),
       (f_get_product_id_by_name('Сахар коричневый'),
        f_get_market_id_by_name('ATB #5'),
        737),
       (f_get_product_id_by_name('Сахарная пудра'),
        f_get_market_id_by_name('ATB #5'),
        686),
       (f_get_product_id_by_name('Желатин'),
        f_get_market_id_by_name('ATB #5'),
        1993),
       (f_get_product_id_by_name('Горький шоколад – 100 г'),
        f_get_market_id_by_name('ATB #5'),
        1828),
       (f_get_product_id_by_name('Гречка'),
        f_get_market_id_by_name('ATB #5'),
        2822),
       (f_get_product_id_by_name('Рис'),
        f_get_market_id_by_name('ATB #5'),
        347),
       (f_get_product_id_by_name('Манка'),
        f_get_market_id_by_name('ATB #5'),
        4522),
       (f_get_product_id_by_name('Горох'),
        f_get_market_id_by_name('ATB #5'),
        260),
       (f_get_product_id_by_name('Сухие грибы'),
        f_get_market_id_by_name('ATB #5'),
        2221),
       (f_get_product_id_by_name('Ваниль'),
        f_get_market_id_by_name('ATB #5'),
        3708),
       (f_get_product_id_by_name('Карри'),
        f_get_market_id_by_name('ATB #5'),
        714),
       (f_get_product_id_by_name('Красный перец'),
        f_get_market_id_by_name('ATB #5'),
        1539),
       (f_get_product_id_by_name('Паприка'),
        f_get_market_id_by_name('ATB #5'),
        3159),
       (f_get_product_id_by_name('Лавровый лист'),
        f_get_market_id_by_name('ATB #5'),
        611),
       (f_get_product_id_by_name('Чай'),
        f_get_market_id_by_name('ATB #5'),
        1949),
       (f_get_product_id_by_name('кофе'),
        f_get_market_id_by_name('ATB #5'),
        4807),
       (f_get_product_id_by_name('Кофе растворимый'),
        f_get_market_id_by_name('ATB #5'),
        3198),
       (f_get_product_id_by_name('Чай черный'),
        f_get_market_id_by_name('ATB #5'),
        172),
       (f_get_product_id_by_name('Чай мятный'),
        f_get_market_id_by_name('ATB #5'),
        2217),
       (f_get_product_id_by_name('Какао порошок'),
        f_get_market_id_by_name('ATB #5'),
        1956);

